add reactions for Insurance <=> Families
vitruv-tools/Vitruv-DSLs pull request #36
Opened 2022-07-12 09:23 UTC by h4uges

- add FamiliesToInsuranceReaction
- add InsuranceToFamiliesReaction
- add tests for FamiliesToInsuranceReaction -> OPEN: change to ViewBasedVitruvApplicationTest
- add first tests for InsuranceToFamiliesReaction -> OPEN: improve test coverage

2022-07-12 11:57 UTC, JanWittler commented
Thanks for the PR. We recently removed the compound reaction triggers (`created and inserted`, `deleted and removed`, #34). Roughly checking your code, I think everything should continue working if you replace the `created and inserted` triggers with `inserted` triggers.

2022-07-22 09:36 UTC, h4uges commented
FamiliesToInsuranceTests - testDeleteFamilyRegister() causes an stack overflow
-> discuss if this a problem in the reaction or in the way the test is written

2022-07-26 06:44 UTC, h4uges commented
@HeikoKlare @tsaglam So jetzt könnt ihr mit dem Review beginnen ;)

2022-07-29 11:43 UTC, tsaglam requested changes
I found a few minor issues for you to consider.

2022-07-29 11:43 UTC, tsaglam commented on bundles/tools.vitruv.applications.demo.insurancefamilies/src/tools/vitruv/applications/demo/insurancefamilies/insurance2families/InsuranceToFamiliesHelper.xtend
> +			.append(" should be.")
You could use [template expressions](https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#templates) here if you want. Also in other instances in this class.

2022-07-29 11:43 UTC, tsaglam commented on bundles/tools.vitruv.applications.demo.insurancefamilies/src/tools/vitruv/applications/demo/insurancefamilies/insurance2families/InsuranceToFamiliesHelper.xtend
> +			.append(" before, have after the renaming?")
Also here, for example.

2022-07-29 11:43 UTC, tsaglam commented on tests/tools.vitruv.applications.demo.insurancefamilies.tests/src/tools/vitruv/applications/demo/insurancefamilies/tests/insurance2families/AbstractInsuranceFamiliesTest.xtend
> +			if (insertCount > 0) decideNewOrExistingFamily(FamilyPreference.Existing, 1)
inconsistent formatting: `if()` vs. `if ()`.

2022-07-29 11:43 UTC, tsaglam commented on tests/tools.vitruv.applications.demo.insurancefamilies.tests/src/tools/vitruv/applications/demo/insurancefamilies/tests/insurance2families/AbstractInsuranceFamiliesTest.xtend
> +			if (insertCount > 0) decideNewOrExistingFamily(FamilyPreference.Existing, 1)
Also in lines 129 and 131.

2022-07-29 11:43 UTC, tsaglam commented on tests/tools.vitruv.applications.demo.insurancefamilies.tests/src/tools/vitruv/applications/demo/insurancefamilies/tests/util/InsuranceQueryUtil.xtend
> +		insuranceDatabase.insuranceclient.filter[c | c.name == firstName + " " + lastName].claimOne
In Xtend you can often shorten these statements from
`c | c.name == firstName + " " + lastName`
to
`name == firstName + " " + lastName`

2022-08-09 14:51 UTC, tsaglam approved these changes
Looks good!

2022-08-09 14:53 UTC, merged